USERNAME : 1919114514 # 学号
PASSWORD : 1919810    # 密码
REASON : "其他必要事项" # 出入校事由
PROVINCE : "北京市"    # 终点所在省
CITY : "市辖区"        # 终点所在市
DISTRICTS : "海淀区"   # 终点所在区
STREET : "海淀街道"    # 终点所在街道
FULL_REASON : "吃饭"  # 出入校具体事项
TRACK : "翅客"       # 详细轨迹

# 以下配置不建议更改以避免未知错误-------------------------------
# 出入校起点和终点, 默认为燕园到校外
START : 1
END : 7
